export const LOAD_DISCOUNTS = 'LOAD_DISCOUNTS'
export const START_REFRESH = 'START_REFRESH'
export const STOP_REFRESH = 'STOP_REFRESH'
export const TEST_DISCOUNTS = 'TEST_DISCOUNTS'

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES'

